### ISSUE TITLE
Implementierung GPS-Position

### ISSUE THREAD

**Issue by dominiqueweber** [HAFL-FWI/Digital-Forest-Monitoring#12]
Kartenausschnitt der aktuellen GPS-Position des Gerätes anpassen

**Comment by hkfrei** [comment]
GPS ist implementiert und aufgeschaltet auf https://forestmonitoring.lab.karten-werk.ch/. Durck Klick auf den gelben Button mit dem Fadenkreuz wird der location service aktiviert/deaktiviert.
@AlexErb @dominiqueweber bitte testen.

**Comment by christianrosset** [comment]
Sehr schön. Danke !

Von: Hanskaspar Frei <notifications@github.com>
Gesendet: Donnerstag, 10. September 2020 15:14
An: HAFL-FWI/Digital-Forest-Monitoring <Digital-Forest-Monitoring@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [HAFL-FWI/Digital-Forest-Monitoring] Implementierung GPS-Position (#12)


GPS ist implementiert und aufgeschaltet auf https://forestmonitoring.lab.karten-werk.ch/. Durck Klick auf den gelben Button mit dem Fadenkreuz wird der location service aktiviert/deaktiviert.
@AlexErb<https://github.com/AlexErb> @dominiqueweber<https://github.com/dominiqueweber> bitte testen.

**Comment by dominiqueweber** [comment]
Funktioniert wunderbar und ist schön umgesetzt.
