### ISSUE TITLE
Karte per URL teilen

### ISSUE THREAD

**Issue by dominiqueweber** [HAFL-FWI/Digital-Forest-Monitoring#14]
Ausschnitt, Zoomstufe und Layerauswahl wird in URL gespeichert und kann somit geteilt werden.

**Comment by hkfrei** [comment]
Folgende URL Parameter werden unterstützt:

- **basemap=Orthofoto** => Hintergrundkarte
- **layers=karten-werk%3Andvi_decrease_2019_2018** => Kommagetrennte Liste von Layern.
- **opacity=0.8** => Kommagetrennte Liste von Transparenzen für jeden Layer.
- **visibility=true** => Kommagetrennte Liste von Sichtbarkeiteiten für jeden  Layer (ein/aus).
- **rotation=0.377221** => Rotation der Karte in Radian
- **x=823871&y=5930503** => Zentrumskoordinate in EPSG:3857 (Web Mercator)
- **zoom=15.9267** => Zoomstufe

Die Parameter beginnen jeweils mit einem "**?**" und werden durch "**&**" voneinander getrennt.
Bei jeder manipulation der Karte oder beim hinzufügen eines Layers, werden die Parameter aktualisiert.

Um Ansichten zu teilen, kann die URL kopiert und weitergegeben werden.

<br />Beispiel:<br />
[https://forestmonitoring.lab.karten-werk.ch/veraenderung?basemap=Orthofoto&layers=karten-werk%3Andvi_decrease_2019_2018&opacity=0.8&rotation=0.377221&vhm=on&visibility=true&x=823871&y=5930503&zoom=15.9267](https://forestmonitoring.lab.karten-werk.ch/veraenderung?basemap=Orthofoto&layers=karten-werk%3Andvi_decrease_2019_2018&opacity=0.8&rotation=0.377221&vhm=on&visibility=true&x=823871&y=5930503&zoom=15.9267)

Ein Problem gibt es noch bei den natürlichen Störungen (Sommersturmschäden). Dort wird momentan immer auf Nussbaumen gezoomt und die Koordinaten aus der URL übersteuert. 

Frage @AlexErb @dominiqueweber: 
Kann man den Zoom auf Nussbaumen rausnehmen um eine Positionierung via URL zu ermöglichen?

**Comment by AlexErb** [comment]
Ja, den Zoom kannst du gerne rausnehmen. Danke!
