### ISSUE TITLE
Fehler im Style bei Darstellung in ArcGIS

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#69]
In ArcGIS funktioniert teilweise der Style nicht, insbes. werden Werte > -0.1 nicht transparent angezeigt:
![grafik](https://user-images.githubusercontent.com/51905171/81573412-bd6a4780-93a4-11ea-9d24-15ed6de44a28.png)

**Comment by hkfrei** [comment]
Das Problem war, dass man auf dem Geoserver den Layerstil nicht als "**Colorramp**" sondern als "**Interval**" definieren muss. Ansonsten werden in ArcGis die noData Werte mit einer Farbe versehen...
Neue Stildefinition: (**das Type Attribut lautet auf "intervals"**)
```
<sld:ColorMap type="intervals">
               <sld:ColorMapEntry quantity="-1" color="#7f0000" label="-1"/>
              <sld:ColorMapEntry quantity="-0.4" color="#b30000" label="-0.4"/>
              <sld:ColorMapEntry quantity="-0.3" color="#d7301f" label="-0.3"/>
              <sld:ColorMapEntry quantity="-0.25" color="#ef6548" label="-0.25"/>
              <sld:ColorMapEntry quantity="-0.2" color="#fc8d59" label="-0.2"/>
              <sld:ColorMapEntry quantity="-0.15" color="#fdbb84" label="-0.15"/>
              <sld:ColorMapEntry quantity="-0.1" color="#fdd49e" label="-0.1" opacity="0.498039"/>
              <sld:ColorMapEntry quantity="-0.05" color="#fee8c8" label="-0.05" opacity="0"/>
            </sld:ColorMap>
```
Alte Stildefinition (**fehlerhaft in ArcGis, das Type Attribut lautet auf "ramp"**):
```
<sld:ColorMap type="ramp">
               <sld:ColorMapEntry quantity="-1" color="#7f0000" label="-1"/>
              <sld:ColorMapEntry quantity="-0.4" color="#b30000" label="-0.4"/>
              <sld:ColorMapEntry quantity="-0.3" color="#d7301f" label="-0.3"/>
              <sld:ColorMapEntry quantity="-0.25" color="#ef6548" label="-0.25"/>
              <sld:ColorMapEntry quantity="-0.2" color="#fc8d59" label="-0.2"/>
              <sld:ColorMapEntry quantity="-0.15" color="#fdbb84" label="-0.15"/>
              <sld:ColorMapEntry quantity="-0.1" color="#fdd49e" label="-0.1" opacity="0.498039"/>
              <sld:ColorMapEntry quantity="-0.05" color="#fee8c8" label="-0.05" opacity="0"/>
            </sld:ColorMap>

```
Bei mir werden die WMS Services nun auch in ArcGis korrekt angezeigt. 
@AlexErb  bitte prüfen.

**Comment by AlexErb** [comment]
Geprüft - passt wunderbar :-)

**Comment by AlexErb** [comment]
Habe gerade die neuen Use Case 3 Daten per WMS in ArcMap geladen und leider tritt der Fehler hier wieder auf...
![grafik](https://user-images.githubusercontent.com/51905171/96450560-a878c680-1216-11eb-9ff7-490851a375cd.png)

**Comment by hkfrei** [comment]
Das ist komisch, die Einstellungen sind genau gleich wie bei den jährlichen Veränderungen. Ich werde dem nachgehen.
Folgender Workaround ist aber schon jetzt möglich:

**1. Öffne WMS Layer properties**
![wms_layer_properties](https://user-images.githubusercontent.com/6850977/96559435-55a61a00-12bd-11eb-9305-ac90c2a8cccb.jpg)

**2. Setze die Hintergrundfarbe auf Weiss**
![background_color_white](https://user-images.githubusercontent.com/6850977/96559632-956d0180-12bd-11eb-87ec-cc90ca094570.jpg)

**3. Hintergrundfarbe transparent anklicken und übernehmen/speichern.**
![make_background_color_transparent](https://user-images.githubusercontent.com/6850977/96559825-d36a2580-12bd-11eb-90d3-7895e9cb37a5.jpg)

So werden die halbtransparenten Zwischenflächen nicht angezeigt (Wert 0)

**Comment by AlexErb** [comment]
> 
> 
> Das ist komisch, die Einstellungen sind genau gleich wie bei den jährlichen Veränderungen. Ich werde dem nachgehen.

... gleiche Frage ;-) Kann ich das schliessen @hkfrei ?

**Comment by hkfrei** [comment]
Falls der Workaround reicht, kann man das Issue schliessen. Die Alternative wäre, ein diskretes Raster mit genau den nötigen Kategorien zu erstellen und alle anderen Werte auf noData zu setzen. Dies würde allerdings einen zusätzlichen Geoprocessing Schritt beim Generieren der Raster bedeuten. Der Entscheid liegt bei Euch.

**Comment by AlexErb** [comment]
Ist durch die neuen Daten für UC1 gelöst, sollte aber bei der Neuberechnung von UC3 berücksichtigt werden.

**Comment by AlexErb** [comment]
Leider tritt das Problem (Transparenz WMS Dienst) jetzt mit den neuen UC3 Daten wieder auf - und auch dein beschriebener Workaround ändert daran leider nichts :( 
Da es mit den UC1 Daten ja schon mal funktioniert hat... könntest du dem nochmal nachgehen, @hkfrei ?

**Comment by hkfrei** [comment]
Ich 👀

**Comment by hkfrei** [comment]
Es ist genau das selbe Problem wie bei UC1:
![image](https://user-images.githubusercontent.com/6850977/124234010-c4f23000-db13-11eb-93f8-da7f3b98f036.png)

- Im Raster ist der Wert  **-32767** als noData definiert, wird aber im Style Grau dargestellt.
- Der transparente Wert 0 ist hingegen nicht noData sondern tatsächlich 0.
- ArcGis kann leider im WMS keine transparenten Werte welche nicht noData sind darstellen.

Die Lösung ist, den transparenten Wert (0) als noData zu klassieren und den Wert -32767 als -32767 (oder irgend etwas anderes aber nicht noData).

Es beudeutet leider, dass man alle Raster reklassieren muss.

**Comment by AlexErb** [comment]
> 
> 
> Ich 👀

Ja, in Bezug auf deinen Post vom 14.9.20 ... damals konntest du einfach was in den Einstellungen auf dem Geoserver ändern ;-). Aber ist gut, dann werde ich diese Reklassierung noch machen für die Geodienste, vermutlich aber erst im August.

**Comment by hkfrei** [comment]
Ah ja genau,  du hast recht. Ich habe die Anpassung jetzt gemacht. Wenn man in ArcGis nun gemäss https://github.com/HAFL-FWI/Digital-Forest-Monitoring/issues/69#issuecomment-712681821 vorgeht, werden die weissen Flächen transparent.
Die nachhaltigere Lösung ist aber sicher den Wert 0 als noData zu klassieren.

**Comment by AlexErb** [comment]
Ich lade die neu klassifizierten Raster heute noch hoch und schliesse hiermit das issue :)
