### ISSUE TITLE
Mehr Zeilenabstand beim Text auf der Startseite

### ISSUE THREAD

**Issue by dominiqueweber** [HAFL-FWI/Digital-Forest-Monitoring#72]
Ein Detail, aber etwas mehr Zeilenabstand wäre gut:
![image](https://user-images.githubusercontent.com/1673692/89879242-ec21d500-dbc2-11ea-98ff-0196cae00da0.png)

**Comment by hkfrei** [comment]
Kam durch einen CSS Fehler meinerseits zustande. Sollte jetzt behoben sein.
