### ISSUE TITLE
Layer können mehrfach hinzugefügt werden

### ISSUE THREAD

**Issue by dominiqueweber** [HAFL-FWI/Digital-Forest-Monitoring#75]
Wie reproduzieren:
1. https://forestmonitoring.lab.karten-werk.ch/vitalitaet
2. Layer hinzufügen (Jun/Jul 2019)
3. Jahr wechseln >2018
4. Jahr erneut wechseln > 2019
5. Gleichen Layer erneut hinzufügen

![image](https://user-images.githubusercontent.com/1673692/90378764-0e5f9b00-e07a-11ea-9e54-69dd7b0dc12b.png)

**Comment by hkfrei** [comment]
Aus meiner Sicht konnte ich das Problem beheben. Bitte @dominiqueweber, @AlexErb bei Gelegenheit testen...

**Comment by dominiqueweber** [comment]
Ich bestätige, das Problem ist gelöst.
