### ISSUE TITLE
Beim Wechsel des Kartenviewers werden Layer nicht zurückgesetzt

### ISSUE THREAD

**Issue by dominiqueweber** [HAFL-FWI/Digital-Forest-Monitoring#78]
Reproduktion des Fehlers:
1.) Kartenviewer jährliche Veränderung öffnen
2.) Zurück via Home Icon
3.) Kartenviewer Vitalität öffnen
4.) Layer von jährliche Veränderung wird angezeigt und kann nicht mehr entfernt werden

![image](https://user-images.githubusercontent.com/1673692/92736759-d860be80-f37a-11ea-8f8f-ed8bc59c8440.png)

**Comment by hkfrei** [comment]
Danke für den Hinweis Dominique. Das Ausrufezeichen stand am falschen Ort...🤯.  🤗. 
Siehe: https://github.com/HAFL-FWI/Digital-Forest-Monitoring/commit/85b762900bda18d3878c1d7861e5336a9fd0ef53
