### ISSUE TITLE
Grauer Bereich GPS Lokalisierung

### ISSUE THREAD

**Issue by dominiqueweber** [HAFL-FWI/Digital-Forest-Monitoring#79]
Auf meinem Desktop kann die Position nicht genau bestimmt werden, dann ist der Suchkreis sehr gross. Habe ich bereits reingezoomt und klicke dann auf das GPS-Icon, wird der ganze Ausschnitt halbtransparent grau bis ich das GPS-Icon erneut anklicke. Wenn ich aber nicht weiss, das ich das GPS-Icon wieder anklicken muss, kriege ich den halbtransparenten Overlay nicht weg.

![image](https://user-images.githubusercontent.com/1673692/93973340-5312dc00-fd74-11ea-8e76-b4959377224a.png)

**Comment by hkfrei** [comment]
@dominiqueweber Was wäre aus deiner Sicht das erwartete Verhalten der Applikation in diesem Fall?

**Comment by dominiqueweber** [comment]
> @dominiqueweber Was wäre aus deiner Sicht das erwartete Verhalten der Applikation in diesem Fall?

Ich hätte einen kleineren Suchradius erwartet (wie wird die Grösse berechnet?). Evtl. das Suchen abschalten (nach 1 min), falls sich die Position nicht ändert und die Genauigkeit unverändert > 100 m ist?

**Comment by hkfrei** [comment]
Die Grösse des Genauigkeitsradius wird vom Browser, anhand der verfügbaren Ressourcen, (GPS, Mobilfunkmasten, Serverstandorte) berechnet.
Was man machen könnte ist bei einem sehr grossen Radius, eine Meldung anzuzeigen die sagt, dass man sich vermutlich auf einem Desktop Computer befindet und GPS wenig Sinn macht. Zudem könnte man einen Hinweis platzieren, wie das GPS wieder abgeschaltet werden kann. Das automatische Deaktivieren wäre auch eine Option. Aus meiner Sicht müsste aber dann auch zwingend ein Hinweis dargestellt werden, wieso das GPS deaktiviert wurde. Ansonsten könnte der User die Aktion als "willkürlich" wahrnehmen.

**Comment by dominiqueweber** [comment]
Du hast recht, so ganz trivial ist das nicht. Vielleicht eine Meldung nach einer gewissen Zeit mit der Möglichkeit das GPS abzuschalten wäre nicht schlecht. Würde dem jetzt aber nicht höchste Priorität geben.

**Comment by hkfrei** [comment]
Alles klar 👍 . Ich schaue es noch mit @AlexErb an sobald Sie wieder aus den Ferien zurück ist. Dann können wir es allenfalls für einen der nächsten Sprints planen.

**Comment by AlexErb** [comment]
> Was man machen könnte ist bei einem sehr grossen Radius, eine Meldung anzuzeigen die sagt, dass man sich vermutlich auf einem Desktop Computer befindet und GPS wenig Sinn macht. Zudem könnte man einen Hinweis platzieren, wie das GPS wieder abgeschaltet werden kann. 

... finde ich eine sehr gute Lösung!

**Comment by hkfrei** [comment]
Ok, dann nehme ich das für den nächsten Sprint auf.

**Comment by AlexErb** [comment]
> 
> 
> Ok, dann nehme ich das für den nächsten Sprint auf.

Kann ich das Issuee schliessen, @hkfrei, oder steht das noch aus?

**Comment by hkfrei** [comment]
Ist noch offen. Kostenmässig rechne ich mit maximal 1500.- Falls das Budget reicht, würde ich das Issue im Februar umsetzen.

**Comment by AlexErb** [comment]
Okay, da muss ich erst Rücksprache halten. Ich melde mich!

**Comment by AlexErb** [comment]
Also, grünes Licht für die Umsetzung :-)

**Comment by hkfrei** [comment]
Super! Dann plane ich eine April Sprint und werde das Issue dort erledigen.

**Comment by hkfrei** [comment]
Bei einer GPS Genauigkeit von einem Radius > 100m wird nun folgende Meldung angezeigt:

![image](https://user-images.githubusercontent.com/6850977/114657785-09c6b180-9cf1-11eb-9789-2c1c74c704ec.png)

Der Radius beträgt in diesem Beispiel < 100m, weil ich ihn zu Testzwecken runterschrauben musste. (Das WLAN im Büro ist genauer als 100m ;-))
Wäre das eine Lösung?
