### ISSUE TITLE
Neue Daten Use Cases 1 & 3 rechnen und hochladen

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#80]
Die neuen Daten für Use Case 1 (Diff 2019-2020) sind auf dem Switch Drive (Use Cases Testdaten > Use Case 1). Die Daten für Use Case 3 folgen.

**Comment by AlexErb** [comment]
Die neuen Daten für Use Case 3 sind jetzt auch hochgeladen (Use Cases Testdaten > Use Case 3). Interessanterweise gibt es tendenziell weniger/schwächere "Anomalien" als im Vorjahr...

**Comment by hkfrei** [comment]
@AlexErb  Super! Ich werde die neuen Daten morgen implementieren.

**Comment by hkfrei** [comment]
@AlexErb wie stylen wir die neuen Daten? @dominiqueweber hat mir im Juni den Link zu einem interessanten Tool geschickt, mit dem Farbveräufe generiert werden können. https://gka.github.io/palettes/
Aus meiner Erfahrung kenne ich https://colorbrewer2.org/. Was meinst Du, sollen wir die Stile generell anhand dieser Tools überdenken und neu definieren?

**Comment by AlexErb** [comment]
Ja, das können wir sehr gerne. Magst du einfach einen Vorschlag machen?

**Comment by hkfrei** [comment]
Die neuen Daten für UC1 und UC3 sind online.
Folgende Farbschemen habe ich implementiert:

- **Rot => ndvi_decrease_2020_2019** (Dieses Schema sollte meiner Meinung immer der aktuellste Datensatz bekommen, es ist meiner Meinung nach das beste.
<img width="171" alt="red" src="https://user-images.githubusercontent.com/6850977/95958829-ff8b2f80-0e01-11eb-8da3-69b8e9213bfc.png">

- **Grün => ndvi_decrease_2018_2017**
<img width="171" alt="green" src="https://user-images.githubusercontent.com/6850977/95958867-09149780-0e02-11eb-84ed-fb3ab8a6c711.png">

- **Blau => ndvi_decrease_2019_2018**
<img width="171" alt="blue" src="https://user-images.githubusercontent.com/6850977/95958897-12056900-0e02-11eb-96ef-c09cb4db229a.png">

- **Violet => ndvi_decrease_2017_2016**
<img width="171" alt="violett" src="https://user-images.githubusercontent.com/6850977/95958919-19c50d80-0e02-11eb-8108-2bc21ea377f1.png">

**Comment by AlexErb** [comment]
Super, sieht gut aus finde ich!

Eine Frage, was haben wir da gerade für ein Luftbild drunter?

**Comment by hkfrei** [comment]
Es ist das aktuellste Orthofoto der Swisstopo. Es setzt sich momentan aus den Flugjahren 2017 bis 2019 zusammen.
Übersicht: https://s.geo.admin.ch/83a0712ebb
