### ISSUE TITLE
Umzug auf waldmonitoring.ch

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#81]
Christian wird morgen einen Webspace inkl. Zugriff für den Entwickler bei infomaniac veranlassen. Thomas hat die Swisstopo Dienste für waldmonitoring.ch freischalten lassen und hätte den Umzug wenn möglich gerne vor dem 21.10.2020 erledigt.

@hkfrei , passt das für dich, und brauchst du sonst noch etwas, um den Umzug in die Wege zu leiten?

**Comment by hkfrei** [comment]
@AlexErb Das passt für mich. Ich brauche nur noch die nötigen Angaben um mich vie FTP auf den Server von infomaniac verbinden zu können.

**Comment by AlexErb** [comment]
Schicke ich dir gleich per Mail. Musste die Weiterleitung raus nehmen damit das funktioniert hat mit dem FTP Zugang... hab das jetzt dafür im HTML File eingefügt, das klappt aber je nach Browser nur mittels "Umleitung"... das kannst du sicher besser und wäre evtl. gut das kurz zu ändern, sodass die Weiterleitung wieder wie gewohnt funktioniert. Danke!

**Comment by AlexErb** [comment]
Die Daten sind jetzt auf http://waldmonitoring.jcloud.ik-server.com - danke Hanskaspar! Allerdings gibt es jetzt das Problem, dass die Ortophotos nicht funktionieren, weil die ja nur für waldmonitoring.ch freigeschaltet sind. Hannes ist dran, die Domain zu "zügeln", das kann aber wegen komplizierter Verantwortlichkeiten evtl. noch ein paar Tage dauern.

Ausserdem scheint mir insbes. Use Case 2 wesentlich langsamer zu laden als vorher... ist das ein Serverproblem?

@hkfrei, könntest du vielleicht einen entsprechenden Hinweis platzieren, dass wegen Umzug die Ortophotos gerade nicht verfügbar sind? Oder hast du einen besseren Vorschlag wie wir damit umgehen?

**Comment by hkfrei** [comment]
Es gibt momentan noch verschiedene Probleme:
Wegen CORS (https://en.wikipedia.org/wiki/Cross-origin_resource_sharing <https://en.wikipedia.org/wiki/Cross-origin_resource_sharing>) können im Moment die Services der Swisstopo nicht genutzt werden. Wie Alex richtig schreibt ist die Domain waldmonitoring.com <http://waldmonitoring.com/> bei Swisstopo nicht freigeschaltet.
Zudem war CORS auch bei unserem Geoserver ein Problem, wir haben dieses aber soeben behoben. Die WMS mit den überlagerten Themen, insbesondere auch UC2 funktionieren nun wie gehabt.
Es fehlt ein SSL Zertifikat (https://…) für diese Domäne. Dies sollte unbedingt noch eingerichtet werden bevor umgestellt wird. Die Browser zeigen sonst „nicht sicher“ in der URL Bar an und dies schreckt die User -zu Recht- ab.
 

Ich meine, wir sollten die Umleitung nach forestmonitoring beibehalten bis die Domäne https://waldmonitoring.ch <https://waldmonitoring.ch/> sauber funktioniert. Es macht keinen Sinn von einem Provisorium ins nächste zu zügeln.

**Comment by AlexErb** [comment]
Ok alles klar.
> 
Ich meine, wir sollten die Umleitung nach forestmonitoring beibehalten bis die Domäne https://waldmonitoring.ch <https://waldmonitoring.ch/> sauber funktioniert. Es macht keinen Sinn von einem Provisorium ins nächste zu zügeln.
Und ja, da gebe ich dir völlig recht :)

**Comment by Hannes-Ole** [comment]
Die Domain [https://waldmonitoring.ch](https://waldmonitoring.ch) läuft nun, inkl. der Swisstopo Services und SSL-Zertifikat. Ich habe alle Tools durchgeklickt, scheint alles zu funktionieren. Auch die Geschwindigkeit ist m.E. ähnlich wie [https://forestmonitoring.lab.karten-werk.ch/](https://forestmonitoring.lab.karten-werk.ch/).
Ich schließe damit das Issue. Testet aber gerne nochmal alles auch im Hinblick auf Performance und öffnet den Issue ggf. nochmal. Die Daten liegen nun auf einer skalierbaren Cloud-Lösung, ggf. können wir mehr Ressourcen zur Verfügung stellen.
