### ISSUE TITLE
Qualitätskontrolle Vitalitäts-Karten

### ISSUE THREAD

**Issue by dominiqueweber** [HAFL-FWI/Digital-Forest-Monitoring#82]
Wunderbar das die neuen Daten aufgeschaltet sind (#80), es gibt bereits Bedarf (z.B. SBB Pilot Vitalität). 

Bei der [Vitalitäts-Karte Aug/Sept 2020](https://forestmonitoring.lab.karten-werk.ch/vitalitaet?layers=kartenwerk%3Andvi_anomaly_2020_08-09&opacity=1&visibility=true&x=886450&y=5966234&zoom=9.0000) scheint die Abdeckung durch verschiedene Orbits jedoch einen starken Einfluss zu haben. @AlexErb könntest du dies prüfen und ist sowas wie eine Qualitätskontrolle geplant/integriert? Mir scheint dies wichtig, da mehr und mehr Leute auf die Daten zugreifen (obwohl natürlich immer noch klar als Test deklariert).

![image](https://user-images.githubusercontent.com/1673692/95984387-610fc600-0e23-11eb-9e3a-438d2170d173.png)

**Comment by AlexErb** [comment]
Ja, du hattest Recht. Untenstehend die Anzahl Aufnahmen (von rot=1 bis hellgrün=23; falls es mehrere Bilder zu einem Datum gibt werden diese zusammengezählt) nach der Ausmaskierung der Wolken basierend auf dem GEE Script für August-September 2020 (reference period) . Ich werde diese Layer für die anderen 2-Monats-Fenster sowie die jeweiligen zugehörigen Referenzperioden auch mal noch generieren, und dann müssen wir uns überlegen wie wir damit umgehen, z.B. ausmaskieren oder Warnhinweis, und ab welchem Schwellenwert.
![grafik](https://user-images.githubusercontent.com/51905171/97584921-d7eab880-19f8-11eb-9758-c7a50ee935c6.png)

**Comment by dominiqueweber** [comment]
Gute Grafik! Schon erstaunlich das es für gewisse Regionen kein brauchbares Bild gibt innerhalb von zwei Monaten. Falls dies wirklich der Fall ist, dann wäre Ausmaskieren wohl sinnvoll/zwingend notwendig.

**Comment by dominiqueweber** [comment]
Es gibt eine neue Cloud Probabilty Maske die, so habe ich gehört, gut/besser ist: https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_CLOUD_PROBABILITY

Würde sich sicher lohnen dies zu prüfen, den ich vermute das nicht gefilterte Wolken (auch Schleierwolken etc.) für einen Grossteil der False-Positive verantwortlich sind.

**Comment by AlexErb** [comment]
Die Cloud Probability Maske scheint wirklich besser zu sein. Es gibt auch noch weitere Möglichkeiten z.B. zusätzlich Berücksichtigung von Wolkenschatten (> Beispiel [hier](https://developers.google.com/earth-engine/tutorials/community/sentinel-2-s2cloudless)). Habe ich beides in der GEE implementiert und funktioniert jetzt soweit. Die erweiterte Variante enthält jedoch diverse, vermutlich teilw. regionsspezifische Parameter, und ich bin mir nicht sicher ob eine generalisierte Anwendung mit "ins Blaue hinein geschätzten" Parametern Sinn macht. @Hannes-Ole, können wir auch evtl. später wieder aufgreifen bzgl. accuracy proof / Validierung?

Ansonsten würde ich jetzt als Verbesserung erstmal vorschlagen:

- Verwendung neuer Wolkenmaske basierend auf S2_CLOUD_PROBABILITY
- zusätzlich Ausmaskierung, falls für die Berechnung des Medians der monitoring period nicht mindestens 3 (oder mehr?) wolkenfreie Aufnahmen zur Verfügung stehen

... comments erwünscht :)

**Comment by dominiqueweber** [comment]
Im Austausch an der WSL bin ich auf den [MAD](https://en.wikipedia.org/wiki/Median_absolute_deviation) gestossen, eine robuste Alternative zum SD (verwendet im [Anomalien-Skript](https://github.com/HAFL-FWI/Digital-Forest-Monitoring/blob/master/methods/use-case3/ndvi_anomaly_gee_script.txt)). Hat bei uns besser funktioniert mit Ausreissern (Wolken, Schatten) - weniger Artefakte im Produkt. Das wäre evtl. auch einen Versuch wert zu Testen ob das die Qualität erhöht.

@AlexErb S2_CLOUD_PROBABILITY finde ich eine gute Idee. Ausmaskieren auch, ob n>=3 reicht, hängt auch davon ab, ob ihr Fehler im Produkt akzeptiert oder lieber weniger Fläche abdecken wollt?! Spontan hätte ich gesagt 3 ist knapp.

**Comment by AlexErb** [comment]
Lustig, der ist mir tatsächlich auch mal in den Kopf gekommen, hatte den in meiner MA verwendet... aber umso besser, dann werde ich das auf jeden Fall mal testen.
Danke für dein Feedback!

**Comment by AlexErb** [comment]
Ich bin dabei, alles neu zu rechnen mit a) verbesserter Wolkenmaske, b) Ausmaskierung, falls für die Berechnung des Medians der monitoring period nicht mindestens 4 wolkenfreie Aufnahmen zur Verfügung stehen, c) Verwendung der median absolute deviation anstatt SD. Sobald fertig, lade ich die neuen Daten wiederum auf den Switch Drive und gebe dir dann Bescheid, @hkfrei. Der Style bleibt gleich, wir sollten aber dann noch einen Hinweis auf die Ausmaskierung einbauen.

**Comment by AlexErb** [comment]
So, endlich endlich sind die neuen Daten auf dem Switch Driver (unter Use Case 3 > NEU 2021), incl. einem neuen style file! Den Info-Text sollten wir dann auch noch anpassen, ich schicke dir einen Vorschlag...
Danke fürs hochladen :)

**Comment by hkfrei** [comment]
@AlexErb Ich habe für die Daten noch "innerTiles" und "overviews" generiert (Performanz). Sie sind jetzt aufgeschaltet. Aus meiner Sicht sieht es sehr gut aus ;-)

**Comment by AlexErb** [comment]
Super danke :) Kannst du es auch wieder sowohl als WMS als auch WFS verfügbar machen?

**Comment by hkfrei** [comment]
WCS/WMS sind online.
