### ISSUE TITLE
Bereitstellung Daten zum Download

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#84]
Hannes und ich hatten mal überlegt, ob es evtl. besser wäre, die Daten direkt zum Download anzubieten anstatt nur via WMS & Co... Bin mir aber selber nicht sicher, ob das wirklich einen Mehrwert bringen würde. Könnten wir beim nächsten Workshop ggf. mal abfragen. @hkfrei, wie denkst du aus technischer Sicht darüber, sind die Daten zu gross oder wäre das einfach machbar?

**Comment by hkfrei** [comment]
Ich finde es eine gute Idee als **Ergänzung** zum WMS.
Alternativ könnte man auch einen WCS Service bereitstellen. Dies ist analog dem WFS aber für Rasterdaten. Das heisst, man bekommt nicht nur ein Bild wie beim WMS, sondern das tatsächliche Raster mit all seinen Werten. Im GIS verhält es sich dann so, als hätte man das Raster lokal. Geoserver unterstützt WCS ich müsste ihn nur aktivieren. Wenn man es über den Download zur Verfügung stellen möchte, müsste man die Raster auf einem Webserver bereitstellen und die Applikation entsprechend um einen Download Button (oder so) erweitern. Allenfalls sollte man dann auch ein Layerfile für QGIS und ArcGis mit der Standard Abbildung wie wir sie verwenden bereitstellen.

**Comment by hkfrei** [comment]
![image](https://user-images.githubusercontent.com/6850977/108726192-6db9ce80-7527-11eb-9205-14ee1da0256c.png)

Zum Testen habe ich den WCS Service freigeschaltet. Die obige Grafik zeigt, wie man ihn in QGIS einbinden kann. Da die gesamten Daten übertragen werden, braucht es eine schnelle Leitung ;-) Bei mir klappen nur die Anomalien halbwegs zügig, die ndvi sind langsam. Bin gespannt wie es bei Euch aussieht.

**Comment by Hannes-Ole** [comment]
Super, vielen Dank dir. Habe es eben getestet: Mit den Anomalien hatte ich etwa 1 Minute Ladezeit bis schweizweit Kacheln da sind. Für die NDVI_decrease layer war die Schweizweite Übersicht in etwa 2 Minuten da, während der Ladezeit wurden 3x "Timeouts" der Datenrequests angezeigt.
Ich wollte auch den Export als Tif getestet: 

![grafik](https://user-images.githubusercontent.com/72789281/108811896-5ffb5c00-75ae-11eb-87a1-e1b4eb164b59.png)

Das klappt grundsätzlich, ist aber für den NDVI_decrease Layer gerade bei 2% und schätzt eine Download-Zeit von 3 Stunden. Das Dateisystem hat für den Download 5,96 GB angezeigt... ist das die Größe, mit der das auf dem Server liegt? Oder liegt das an Mosaik-Pyramiden, dass die Layer so groß sind? 
Der  NDVI_anomaly Layer zeigt eine Download Zeit von 1 Stunde und wurde mit 1,5 GB angelegt.
**Evtl. könnten wir für schnellere Übertragungen auch von Floats auf Integer-Tiffs konvertieren.**

**Comment by hkfrei** [comment]
Auf dem Server haben die NDVI mit den jährlichen Veränderungen eine Grösse von rund 8.7 GB (inkl. der Overviews und Pyramiden). Die NDVI Anomalien liegen bei rund 2.2GB auch inkl. Overview/Pyramiden.
Eine Konvertierung nach Integer fände ich sehr sinnvoll. Ich glaube, man könnte damit auch Issue #69 lösen indem man die transparenten Werte auf NoData setzt. Die Overviews braucht es wegen der Geoserver Perfomanz halt trotzdem, aber die Raster würden sicher deutlich kleiner. Vielleicht könnte man es bei Gelegenheit an einem Beispiel testen?

**Comment by AlexErb** [comment]
Ich lade dir die NDVI_Diff_2020_2019 als Int16 auf den Switch Drive, ok? Grösse ist wie zu erwarten nur noch ca. halb so gross (270 MB), nach reprojection auf epsg 3857 dann noch etwa 500 MB. Falls das nicht reicht, hatten wir auch überlegt, ob evtl. sogar 8 Bit reichen würden an Genauigkeit...

**Comment by hkfrei** [comment]
Habe die Daten heruntergeladen und versucht darzustellen. Allerdings reichen die Werte jetzt von  `-8900 bis -756`und ich habe keine Ahnung wie diese mit den Originalwerten von `-0.6 bis 0.38` korrelieren. Entsprechend kann ich das Raster nicht mit dem derzeitigen Stil darstellen. 

**Vorschlag:**
Wenn schon eine Konvertierung in einen Ganzzahl Datentyp stattfinden soll, dann würde ich dies über eine Reklassierung tun. So kann man selber bestimmen welche Werte man im Resultat erhält.

**Beispiel:**
Die Reklassierung würde ich gemäss unseren Stilklassen vornehmen.
Originalwert        | Reklassiert             | Bemerkung  |
| --------------- |:------------------:| ------------:|
| -0.05              | NoData          | Wert wird momentan transparent dargestelstellt. Es mach deshalb keinen Sinn die Daten überhaupt zu speichern.    Evtl. wäre das die Lösung für #69      |
| -0.1     | 10   |   -   |
| -0.15  | 15   |   -   |
| -0.2    | 20  |-      |
| -0.25  | 25  |-      |
| -0.3    |30   |-      |
| -0.4    |40   |-      |
| -1       |100  |-      |


Somit würde auch ein 8Bit Datentyp mit 256 Werten locker reichen. Wichtig ist natürlich, dass man den Usern erklärt wie die Werte zu interpretieren sind aber dies muss man ja bei Fliesskommazahlen auch 😉.
Was meint Ihr dazu?

**Comment by AlexErb** [comment]
Ich bin mir nicht ganz sicher, ob ich eine solche Diskretisierung der Daten sinnvoll finde... denn insbes. wenn man das Raster als WFS zur Verfügung stellt, ist das ja schon ein Genauigkeitsverlust. Müssen wir diskutieren. Denke wir werden aber auf jeden Fall die Raster auf die eine oder andere Art zu Int konvertieren, die Vektorlayer neu rechnen und den Versatz beheben, und die neuen Raster zusätzlich als WFS zur Verfügung stellen. Ich melde mich :)

**Comment by hkfrei** [comment]
Wollte nur noch sagen, dass das eine das andere nicht ausschliesst. Den WMS könnte man reklassiert publizieren (nur als WMS ohne WCS), dann einen separaten Layer mit den kontinuierlichen Rohdaten als WCS für die User zur Einbindung ins GIS.   Einfach zur Info 😉

**Comment by AlexErb** [comment]
Kann es sein, dass die neuen WCS noch nicht online sind? Wollte sie testen, bin aber nicht fündig geworden...

**Comment by hkfrei** [comment]
Sie sind online unter [https://geoserver.karten-werk.ch/wcs](https://geoserver.karten-werk.ch/wcs). 
Im QGIS ->Browser->WCS->Rechtsklick->neue Verbindung
Heute Nachmittag schalte ich auch noch das Video dazu auf...

**Comment by AlexErb** [comment]
Das klappt bei mir leider nicht... 
![grafik](https://user-images.githubusercontent.com/51905171/113672963-a87f5c80-96b8-11eb-9981-038f755ac7f4.png)

**Comment by hkfrei** [comment]
Ja, wenn du die URL im Browser öffnest, muss du weitere Parameter angeben. Z.B. https://geoserver.karten-werk.ch/wcs?request=getCapabilities

Im QGis reicht https://geoserver.karten-werk.ch/wcs.

 

 

Von: AlexErb ***@***.***> 
Gesendet: Dienstag, 6. April 2021 09:16
An: HAFL-FWI/Digital-Forest-Monitoring ***@***.***>
Cc: Hanskaspar Frei ***@***.***>; Assign ***@***.***>
Betreff: Re: [HAFL-FWI/Digital-Forest-Monitoring] Bereitstellung Daten zum Download (#84)

 

Das klappt bei mir leider nicht...
 <https://user-images.githubusercontent.com/51905171/113672963-a87f5c80-96b8-11eb-9981-038f755ac7f4.png>

**Comment by AlexErb** [comment]
Ja sorry das weiss ich eigentlich, mein Fehler. Klappt super und lädt im QGIS mega schnell :-)
