### ISSUE TITLE
Konsistente Benennung WMS Layer

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#85]
... bitte kurz ersten Eintrag (ndvi_diff_2018_2017_vector) analog bzw. konsistent zu den anderen benennen, um Verwirrung zu vermeiden.... dankeschön :-)
![wms](https://user-images.githubusercontent.com/51905171/108179092-7ebca700-7105-11eb-820d-328f2ed34371.jpg)

**Comment by hkfrei** [comment]
👍  Ist erledigt.
