### ISSUE TITLE
Auffindbarkeit waldmonitoring.ch

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-FWI/Digital-Forest-Monitoring#86]
Momentan taucht die Domain waldmonitoring.ch bei google nur auf, wenn man gezielt nach waldmonitoring.ch sucht. Assoziierte Seiten findet man z.B. mit kombinationen der Stichwörter `waldmonitoring fernerkundung schweiz ch`. Sicherlich ebenso gut wäre es, die Stichwörter `geodaten open-source wissenstransfer forstliche praxis sturmereignis baumvitalität forstliche eingriffe` abzudecken. Wenn das nicht beschränkt ist, können wir die Liste auch nochmal brainstormen und erweitern...

@hkfrei : Kennst du als Webentwickler gute Techniken, die Seite "sichtbarer" im Web zu machen? (ich habe so etwas wie keywords in einem HTML Meta-Tag im Hinterkopf). Oder hast du die gängigen, kostenfreien Dinge bereits gemacht und es ist einfach eine Frage von Zeit / Traffic, bis wir "prominent" werden?
Müssen wir die Seite wiki.waldmonitoring.ch separat behandeln (weil sie auf einem anderen Server liegt)?

**Comment by hkfrei** [comment]
Die wichtigsten Massnahmen wie das `<Title>` und `<meta name="description"...` Tag sind bereits vorhanden. 
Ein Problem ist, dass wir viel Content wie die Karten etc. mit JS sozusagen im Nachgang laden und entsprechend sieht der Google Crawler diesen Inhalt nicht im Source-Code der Page. Aus meiner Erfahrung verbessert sich dies aber mit der Zeit und einer Zunahme des Traffics.

Folgendes habe ich noch ergänzt:
- Ein `<meta name="keywords"` Tag erstellt und mit deinen obigen Stichwörtern ergänzt. Hier kann man beliebige viele Keywords reinschreiben.
- Das `alt="..."` Attribut bei den WMS Legenden eingefügt.

Natürlich gibt es immer Verbesserungspotenzial, aber die Seite steht punkto SEO nicht schlecht da. Die Lighthouse Auswertung ergab
![image](https://user-images.githubusercontent.com/6850977/109273870-0e9fd680-7813-11eb-95d0-f7c8ff175ba8.png)

Ja das WIKI muss separat behandelt werden, es ist eine eigenständige Website.
