### ISSUE TITLE
Versatz Raster- und Vektordaten UC 1

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#87]
Wir haben einen Versatz bei den Raster- und Vektordaten (UC1) festgestellt. Der Fehler liegt in den Originaldaten und scheint bei der Projektion passiert zu sein > [Link zum Script](https://github.com/HAFL-FWI/Digital-Forest-Monitoring/blob/master/methods/use-case1/project.R)
Ich werde das prüfen...

**Comment by AlexErb** [comment]
Das Problem ist soweit gelöst, zudem sieht das Ergebnis durch eine verbesserte resampling method (cubic vs. nearest neighbor) auch glatter aus. Wir müssen diskutieren, ob wir es für alle Jahre nochmal neu rechnen & hochladen wollen oder nur für 2019/2020, und dabei auch gleich #84 mit berücksichtigen.

![grafik](https://user-images.githubusercontent.com/51905171/109982764-803fbf00-7d02-11eb-92f7-9a4365dacb09.png)

**Comment by hkfrei** [comment]
Wahrscheinlich würde durch die Reklassierung (#84) und der einhergehenden Diskretisierung der Daten der Vorteil des cubic resampling ein wenig verwässert, aber ich bin trotzdem dafür die Daten neu zu rechnen und hochzuladen. Oder mindestens könnte man es an einem Beispiel versuchen und schauen wie das Resultat aussieht.

**Comment by AlexErb** [comment]
[Hier](https://drive.switch.ch/index.php/s/vkz037Oj363oacR) lade ich dir die neuen Daten hoch:
- Diff. Raster als Int16 > für den neuen WCS Dienst
- Diff. Raster als Int 16, wobei alle Werte grösser -1000 NA sind > für den Kartenviewer und WMS Dienst
- Vektordaten

Die Diff. Raster für den Kartenviewer würde ich dann mit einem neuen QGIS style file so klassifizieren, dass sie einfach "wie immer" dargestellt werden. Machst du das, @hkfrei, oder soll ich noch ein style file erstellen? Falls ja, kannst du mir ggf. kurz das schicken, was aktuell verwendet wird? Danke :)

**Comment by hkfrei** [comment]
Super wie leicht die Rasterdaten nun sind👍
Ich bin froh wenn du die Styles erstellen kannst. Sende dir gleich die Geoserver style Files per Mail noch zu.

**Comment by hkfrei** [comment]
Die neuen Daten sind nun online. Neben den aktualisierten Vektor und Rasterdaten, gibt es 4 neue WCS Services:

- wcs_ndvi_diff_2017_2016
- wcs_ndvi_diff_2018_2017
- wcs_ndvi_diff_2019_2018
- wcs_ndvi_diff_2020_2019

Diese beinhalten die Rohdaten und können in GIS-Systeme eingebunden werden. Sie werden nur als WCS und nicht auch noch als WMS publiziert.
Gerade umgekehrt ist es bei den "ndvi_decrease_xy_xy" Services. Diese werden nun nicht mehr als WCS, sondern nur noch als WMS publiziert.

Ich bin froh wenn ihr einen Augenschein nehmen könnt ob alles i.O. ist.

**Comment by AlexErb** [comment]
Kannst du bitte noch bei der Legende überall das rote Kreuz raus nehmen, also bei -0.05? Bei manchen Jahren ist es draussen, bei anderen noch drin ;-) Danke!

**Comment by hkfrei** [comment]
Versuche den Browser Cache zu löschen. Dann ist werden die Legenden neu heruntergeladen und die Kreuze sind überall weg.

**Comment by AlexErb** [comment]
Leider liegen Raster- und Vektordaten bei der Einbindung in map.geo.admin.ch noch immer nicht ganz schön übereinander... ich denke, das liegt einfach daran, dass die mit unserem CRS nicht umgehen können, oder? Im QGIS passt alles wunderbar. Denke, wir sollten zumindest irgendwo (z.B. im Wiki) hinweisen...
![grafik](https://user-images.githubusercontent.com/51905171/113674916-0ca32000-96bb-11eb-8522-44d1b6c1490f.png)

**Comment by hkfrei** [comment]
Ja, wenn's im QGIS passt und in map.geo.admin nicht, dann hat es etwas mit der Projektion zu tun. Vermutlich macht OpenLayers hier etwas ein bisschen anders als QGIS. Da wir die Vektor und WCS Daten nicht in unserem Viewer brauchen, könnte man sie eigentlich in der LV95 statt in der WebMercator Projektion anbieten. Evtl. würde das helfen.

**Comment by AlexErb** [comment]
Ja, wobei ich denke dass die Leute vermutlich am ehesten WMS plus Vektordaten in map.geo.admin laden... und die WMS brauchen wir ja wohl im Viewer... also werde ich denke ich einfach einen Hinweis im Wiki einbauen, falls uns nicht noch ne bessere Lösung einfällt ;-)

**Comment by AlexErb** [comment]
Heute ist der Versatz interessanterweise weg... ich schliesse das Issue mal ;)
