### ISSUE TITLE
Video Tutorial WCS

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#88]
@hkfrei, könntest du ein kurzes Video analog zu den anderen beiden machen, sobald der Dienst fertig ist? Fände es schön wenn das konsistent ist und auch von dir kommt. Falls du keine Zeit hast können wir es aber natürlich auch selber machen.

**Comment by hkfrei** [comment]
Video ist online.

**Comment by AlexErb** [comment]
Top, danke!! Toll dass du auch noch die Multiplikation mit 10000 und den Export erklärst :-)
