### ISSUE TITLE
Fehlermeldung bei GPS Positionierung

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#93]
![grafik](https://user-images.githubusercontent.com/51905171/128354742-b5200dd7-fe6f-4557-b645-e59764dae150.png)

**Comment by AlexErb** [comment]
- Warum kommt diese Fehlermeldung & klappt die GPS Positionierung nicht mehr (auf zwei versch. mobilen Geräten und mit unterschiedlichen Browsern getestet)?
- Falls Fehlermeldung, wäre eine verständlichere, "user-freundlichere" Fehlermeldung schön ;-)

**Comment by hkfrei** [comment]
Wahrscheinlich hast du nicht die http**s**:// sondern die nur die http:// Adresse eingegeben. Immer mit https://waldmonitoring.ch/ probieren. Oder Euer SSL Zertifikat hat ein Problem...

**Comment by christianrosset** [comment]
Das war das Problem. Das passt. Danke!

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by AlexErb** [comment]
Tatsächlich :-) Das war uns allerdings auch gar nicht klar. Wäre es aber evtl. möglich, das in die Fehlermeldung zu schreiben für weitere User?

**Comment by hkfrei** [comment]
Die Fehlermeldung wird automatisch vom Browser generiert. Ich schaue bei Gelegenheit, ob man diese "customizen" kann, vermutlich aber eher nicht. Melde mich diesbezüglich wieder.

**Comment by AlexErb** [comment]
Ok alles klar. Vielen Dank dir, auch für die rasche Klärung!

**Comment by hkfrei** [comment]
Ich konnte die Fehlermeldung ergänzen. Nun wird folgendes angezeigt:
![image](https://user-images.githubusercontent.com/6850977/128463398-d96abaa4-c026-49ce-8b75-8bdf9d92a177.png)

Damit das Problem gar nicht vorkommen kann, kann man auf dem Webserver eine automatische Umleitung einrichten. Sobald jemand mit der http:// Adresse kommt, wird er automatisch auf https:// umgeleitet.

**Comment by Rdataflow** [comment]
@AlexErb Es wäre hilfreich, wenn ihr eine permanente Umleitung von http://waldmonitoring.ch auf https://waldmonitoring.ch einrichten könnt (z.B. mittels 301 redirect).
