### ISSUE TITLE
Umleitung http auf https

### ISSUE THREAD

**Issue by AlexErb** [HAFL-FWI/Digital-Forest-Monitoring#94]
> Es wäre hilfreich, wenn ihr eine permanente Umleitung von http://waldmonitoring.ch auf https://waldmonitoring.ch einrichten könnt (z.B. mittels 301 redirect).

siehe #93

**Comment by Hannes-Ole** [comment]
Eine einfache Einstellung im Infomaniak Webhosting Panel habe ich nicht gefunden.
Habe nun im .htaccess file auf dem Server eine entsprechende RewriteRule angelegt. Bei mir funktioniert es in diversen Browsern. Gerne verifizieren, ich bin mir aber sicher genug um das Ticket zu schliessen.

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</IfModule>
```

**Comment by Rdataflow** [comment]
Scheinbar ist diese Einstellung aktuell nicht mehr aktiv?

**Comment by Hannes-Ole** [comment]
@hkfrei Ich habe diese Einstellung in .htaccess manifestiert. Mir war nicht bewusst, dass ein Update deiner webapp .htaccess überschreibt. Ich habe entsprechend die Datei hier im repository geändert und manuell auf dem Server geändert, um nicht den ganzen build-Prozess durchgehen zu müssen. In Zukunft sollte die Einstellung also nicht mehr überschrieben werden.

**Comment by Hannes-Ole** [comment]
https://github.com/HAFL-FWI/Digital-Forest-Monitoring/blob/master/webapp/static/.htaccess

**Comment by hkfrei** [comment]
@Hannes-Ole Ich glaube das einzige Problem war, dass die Änderung im .htaccess File nicht auf git commited wurde. Dadurch habe bei einem `git pull` immer noch die alte Version bekommen und damit überschrieben. Jetzt wo es auch im Repo commited ist, wird es klappen.
